app_blog/urls.py
from . import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'app_blog'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bdInfoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_blog.urls', namespace='blog'))

]

app_blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone



class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    published = PublishedManager()  # Custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

app_blog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from app_blog.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'frontend/post/index.html', {'posts': posts, 'page': page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    return render(request, 'frontend/post/details.html', {'post': post})

templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>BD Pedia || Bangla Pedia || Bangladesh Pedia</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'frontend/css/blog-home.css' %}" rel="stylesheet">


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'app_blog:index' %}">BD Pedia</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app_blog:index' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">SEO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Graphics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Mobiles</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        {% block content %}
        {% endblock %}
        {% include "frontend/partials/right_sidebar.html" %}


    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->

<nav class="navbar navbar-expand-md navbar-light bg-light">

    <div class="container">
        <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">
            <a href="#" class="nav-item nav-link active">About us</a>
            <a href="#" class="nav-item nav-link">Site Map</a>
            <a href="#" class="nav-item nav-link">Contact us</a>
            <a href="#" class="nav-item nav-link">Disclaimer</a>
        </div>

    </div>
    </div>
</nav>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'frontend' %}/vendor/jquery/jquery.min.js"></script>
<script src="{% static 'frontend' %}/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/frontend/partials/right_sidebar.html
<!-- Sidebar Widgets Column -->
<div class="col-md-4">

    <!-- Search Widget -->
    <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
        </div>
    </div>

    <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body text-success">
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>

            <button type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </button>
        </div>
    </div>

    <!-- Side Widget -->
    <div class="card my-4">
        <h5 class="card-header">Recent Post</h5>
        <ul class="list-group">

            <a href="" class="text-decoration-none text-dark">
                <li class="list-group-item">Dapibus ac facilisis in</li>
            </a>

        </ul>

    </div>

    <div class="card my-4">
        <h5 class="card-header">Hot Post</h5>
        <ul class="list-group">

            <a href="" class="text-decoration-none text-dark">
                <li class="list-group-item">Dapibus ac facilisis in</li>
            </a>

        </ul>
    </div>

    <div class="card my-4">
        <h5 class="card-header">Tags</h5>
        <div class="card-body text-success">
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>
            <a type="button" class="btn btn-outline-success btn-sm"
                    style="margin-top: 1px; margin-bottom: 5px;">Primary
            </a>


        </div>
    </div>


</div>

templates/frontend/post/details.html
{% extends 'frontend/base.html' %}

{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% block  content %}


        <!-- Blog Entries Column -->
        <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{ post.author }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on <strong>{{ post.created | timesince }}</strong> ago</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">{{ post.body }}</p>
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>


{% endblock %}

templates/frontend/post/index.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block styles %}

{% endblock %}

{% block  content %}

    <!-- Blog Entries Column -->
    <div class="col-md-8">
        <!-- Blog Post -->
        {% for post in posts %}
            <a class="text-decoration-none text-dark" href="{{ post.get_absolute_url }}">
                <div class="card mb-4 mt-1">
                    <img class="card-img-top" src="{% static 'frontend/images/blog_img.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text">
                            {{ post.body|truncatewords:30|linebreaks }}
                        </p>
                        <a href="{{ post.get_absolute_url }}" class="btn btn-outline-success">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on January 1, 2020 by
                        <a href="#" class="text-success">Django</a>

                    </div>
                </div>
            </a>

        {% endfor %}


        <!--Pagination-->
      <div class="container p-4">
        <div class="pagination justify-content-center">
            <span class="step-links">
              {% if page.has_previous %}
                  <a href="?page=1">&laquo; First</a>
                  <a href="?page={{ page.previous_page_number }}">Previous</a>
              {% endif %}

                <span class="current">
                    Page {{ page.number }} of {{ page.paginator.num_pages }}
                </span>

              {% if posts.has_next %}
                  <a href="?page={{ page.next_page_number }}">Next</a>
                  <a href="?page={{ page.paginator.num_pages }}">Last &raquo;</a>
              {% endif %}
            </span>
            </div>
        </div>
      <!--end of Pagination-->


    </div>


{% endblock %}